                                        <h1 align="center">CLICK-WRAP  LICENSE AGREEMENT </h1>
                                        <p>IMPORTANT  - READ CAREFULLY: This Click-Wrap License Agreement (hereinafter &ldquo;Agreement&rdquo;) is  a legal contract between  you (either an individual or business  entity, hereinafter referred  to as &ldquo;Licensee&rdquo;) and FLSmidth  A/S, a Denmark corporation (hereinafter &ldquo;FLSmidth&rdquo;), for the Fuller®  and other FLSmidth brand compressors' sizing software (the &ldquo;Software&rdquo;).  The term &ldquo;Software&rdquo;  also includes the  resulting calculations and pump curves produced by the use of the Software and any supplied corrections,  bug fixes, enhancements, updates  or other modifications created and supplied by FLSmidth and any user manuals  or other  documentation supplied by FLSmidth in conjunction with the Software.</p>
                                        <p>BY  CLICKING THE &ldquo;ACCEPT&rdquo; BUTTON BELOW,  OR BY DOWNLOADING, INSTALLING OR OTHERWISE USING THE SOFTWARE,  YOU AGREE TO BE BOUND  BY THE TERMS OF THIS AGREEMENT.  IF YOU DO NOT AGREE TO THE TERMS OF  THIS AGREEMENT, DO NOT DOWNLOAD,  INSTALL, OR USE THE SOFTWARE.</p>
										<ol>
                                        	<li><h5>LICENSE TERMS </h5>
                                                  <ol type="a">
                                                    <li><em>Grant of License</em>. Provided  that Licensee is in  material compliance with the terms  and conditions of this Agreement,  Licensor hereby grants to  Licensee, pursuant to the terms and conditions of this  Agreement, a revocable, nonexclusive, nontransferable license (hereinafter  &ldquo;License&rdquo;) to use the Software.</li>
                                                    <li><em>Authorized  Use</em>.  Licensee shall be provided  access to certain information  related to Fuller and other FLSmidth brand compressors, which information shall  be managed by FLSmidth in its sole discretion.  The License granted  hereunder allows  Licensee to use the Software  to size and compare Fuller  and other FLSmidth brand compressors for the sole purpose of evaluating these compressors  in furtherance of a potential purchase of Fuller or other FLSmidth brand  compressors from FLSmidth (&ldquo;Authorized Use&rdquo;).</li>
                                                    <li><em>Restrictions  on Use</em>.  Licensee  agrees to use the Software  only for the Authorized Use and for its own business. Under no circumstances shall Licensee  (i) permit any  unrelated third parties  to use the Software, (ii)  copy or distribute any result produced by  the Software, including any resulting calculations and graphs, or (iii) use  the Software in competition with FLSmidth.</li>
                                                    <li><em>Nature of the Software.</em>  Licensee agrees that the Software is a simulation and  is for information and comparison purposes only.  Licensee agrees that the Software does not  create an offer for sale, warranty or other such representation or obligation  by Licensor with respect to its products.   To receive a firm quote, Licensee must contact Licensor directly, which  quote shall be governed by FLSmidth's then current Standard Terms and  Conditions for Equipment Supply<a name="_GoBack"></a>. </li>
                                                    <li><em>Modifications; Reverse  Engineering</em>.  Licensee agrees that only Licensor  shall have the right to alter,  maintain, enhance or otherwise modify the Software. Licensee shall not disassemble, decompile or reverse engineer the Software  or attempt to do the same.  Licensee shall not permit or assist any third party to disassemble,  decompile or reverse engineer the Software.</li>
                                                    <li><em>Material Terms  and Conditions.  </em>Licensee  specifically agrees that each  of the terms and conditions of this Section  1 are material and that failure  of Licensee to comply  with these terms and conditions  shall constitute sufficient cause for Licensor to terminate  this Agreement. The presence  of this Subsection  1.f shall not be relevant  in determining the materiality of any  other provision or breach of this Agreement  by either Party.</li>
                                                    <li><em>Reservation of Rights.   </em>Licensor hereby reserves  any and  all  rights not expressly  and explicitly granted  in this Agreement, including, but not limited  to, Licensor&rsquo;s right to license  the Software to any third party.</li>
                                                    <li><em>Term of License</em>. Unless otherwise  terminated as set forth  herein, the term of  the License granted hereunder shall extend until the  completion or termination of the Authorized Use. Licensee may terminate  this License at any time by discontinuing its use of the  Software.</li>
                                                    <li><em>Representations by Licensee</em>.  By accepting  this Agreement and/or by using the Software,  Licensee hereby represents and warrants that all information  provided by Licensee to Licensor during the registration process for the Software  is true  and accurate in all material respects. Licensee further represents and warrants  that Licensee has been  duly authorized to enter into  this Agreement for and on  behalf of any person,  company, or other entity specified during the initial  registration process for the Software.   Should either of  these representations prove  false at any time,  Licensor may, in Licensor&rsquo;s sole discretion,  immediately discontinue Licensee&rsquo;s access to and disable Licensee&rsquo;s use  of the Software without notice  and without recourse by Licensee.</li>
                                                    <li><em>Email  Subscription.</em> By accepting  this Agreement and/or by using the Software, Licensee herby allows the Licensor  to email Software updates, other information regarding the Software, and  marketing materials to the email address provided by Licensee. Licensee may opt  out of receiving marketing materials but agrees to continue to receive Software  updates and other information regarding the Software for the duration of the  term.</li>
                                                  </ol>
											</li>                                                
                                        	<li>
                                                <h5>INTELLECTUAL  PROPERTY RIGHTS </h5>
                                                  <ol type="a">
                                                    <li><em>Title</em>.  Licensee  and Licensor agree that Licensor  owns all proprietary rights, including  patent, copyright, trade secret,  trademark and other  proprietary rights, in and  to the Software and any  corrections, bug fixes, enhancements,  updates or other modifications, including custom  modifications, to the  Software and the results provided therefrom,  whether made by Licensor  or any third party. No  title to the Software or the results provided therefrom  is transferred  hereby and Licensee&rsquo;s rights hereunder are strictly  limited as set forth  herein.</li>
                                                    <li><em>Copyrights.</em>  The Software and the results  therefrom is copyrighted by FLSmidth and is protected by United States  copyright and patent laws and international treaty provisions. You may not duplicate  nor distribute the Software or any results therefrom except as provided herein.</li>
                                                    <li><em>Transfers</em>.  Under no circumstances  shall Licensee sell, license,  publish, display, distribute,  or otherwise transfer  to a third party the Software or  any copy thereof, in whole  or  in part, without Licensor&rsquo;s  prior written consent.</li>
                                                  </ol>
											</li>    
                                        	<li>
                                                <h5>WARRANTY;  DISCLAIMER OF WARRANTIES </h5>
                                                  <ol type="a">
                                                    <li><em>Warranty</em>.  Licensor warrants  to  Licensee that the  Software will at all times  substantially comply with  FLSmidth&rsquo;s then current specifications  for  the Software.</li>
                                                    <li><em>Disclaimer</em>.  EXCEPT AS EXPRESSLY  SET FORTH HEREIN, THERE  ARE  NO OTHER WARRANTIES  OF ANY KIND, EITHER EXPRESS  OR IMPLIED, INCLUDING,  BUT  NOT LIMITED TO, WARRANTIES  AS TO TITLE OR INFRINGEMENT OF THIRD-PARTY RIGHTS, MERCHANTABILITY OR  FITNESS FOR A PARTICULAR PURPOSE.  THE SOFTWARE, DOCUMENTATION AND OTHER FILES ARE PROVIDED  &ldquo;AS IS.&rdquo;  FLSMIDTH  AND ITS SUPPLIERS  DO NOT AND CANNOT WARRANT THE PERFORMANCE OR RESULTS  YOU  MAY OBTAIN BY USING THE SOFTWARE.   </li>
                                                  </ol>
											</li>                                                
                                        	<li>
                                                <h5>LIMITATION OF LIABILITY </h5>
                                                <p>IN  NO EVENT WILL FLSMIDTH BE LIABLE TO LICENSEE OR ANY THIRD PARTY FOR LOST OR ANTICIPATED PROFITS, LOSS OF USE, LOSS  OF BUSINESS OPPORTUNITIES, INTERRUPTION OF BUSINESS OR INDIRECT,  SPECIAL, INCIDENTAL, CONSEQUENTIAL, EXEMPLARY OR OTHER SIMILAR  DAMAGES.<strong> </strong>FLSMIDTH'S AGGREGATE LIABILITY IN RESPECT OF  ANY AND ALL CLAIMS WILL BE LIMITED TO ONE HUNDERD ($100.00) DOLLARS. THE  FOREGOING LIMITATIONS APPLY REGARDLESS OF THE CAUSE OR CIRCUMSTANCES GIVING  RISE TO SUCH LOSS, DAMAGE OR LIABILITY, EVEN IF SUCH LOSS, DAMAGE OR LIABILITY  IS BASED ON NEGLIGENCE OR OTHER TORTS OR BREACH OF CONTRACT (INCLUDING  FUNDAMENTAL BREACH OR BREACH OF A FUNDAMENTAL TERM).</p>
											</li>
                                        	<li>
                                                <h5>GENERAL PROVISIONS </h5>
                                                  <ol type="a">
                                                    <li><em>Modifications</em>. FLSmidth  may alter  or revise  the terms of this Agreement by giving Licensee thirty (30) days' notice of  the changes to be made.  If  Licensee does not agree  to accept  the changes, Licensee&rsquo;s sole remedy  shall be to discontinue  Licensee&rsquo;s use of the Software.</li>
                                                    <li><em>Governing  Law/Venue/Jurisdiction</em>. This Agreement shall be governed  by and construed under the laws of the commonwealth  of Pennsylvania, without regard to choice  of law provisions.  The  application of the United Nations  Convention on Contracts for the International Sale  of Goods is expressly  excluded. Venue and jurisdiction shall be  proper only in the  commonwealth of Pennsylvania and each party hereby consents to such exclusive  and personal jurisdiction and venue.</li>
                                                    <li><em>Termination</em>.  Without prejudice to any other  rights, FLSmidth may terminate  this Agreement at any time and  for any reason.  In  such event, FLSmidth may deny access to the Software and Licensee must discontinue  use of the Software.</li>
                                                    <li><em>Severability</em>.  Except as  otherwise set forth in this  Agreement, the provisions of this Agreement  are severable, and if any one or  more such provisions shall be determined  to be invalid, illegal  or unenforceable, in whole or  in part, the validity,  legality and enforceability of any of the  remaining provisions  or portions thereof  shall not in any way be affected  thereby and shall nevertheless be binding between  the parties hereto.  Any such invalid, illegal  or unenforceable provision  or portion thereof  shall be changed and interpreted so as  to best accomplish the objectives of such provision  or portion thereof  within the limits of applicable law.</li>
                                                    <li><em>Complete  Agreement</em>. The parties  agree that this  Agreement is the complete  and exclusive statement of the agreement between  the parties, which supersedes and merges all prior proposals,  understandings and all other  agreements, oral or written,  between the parties  relating to the subject matter.</li>
                                                    <li><em>Waiver</em>.  Any waiver, either expressed  or implied, by either party of any default  by the other in the observance and performance of any of the conditions and/or covenants of duties set forth herein shall not constitute or be construed  as a waiver of any subsequent or other default.</li>
                                                    <li><em>Read and Understood</em>. Licensee  hereby acknowledges that it has  read and understands this  Agreement and agrees to  be bound by its terms.</li>
                                                    <li><em>Headings</em><strong>. </strong>The headings  to the Sections and Subsections  of this  Agreement are included  merely for convenience of reference  and shall not affect the  meaning of the language included therein.</li>
                                                  </ol>
											</li>
										</ol>                                                
